image: golang:latest

stages:
  - build

building:
  stage: build
  script:
    - go get -u github.com/pepa65/horcrux
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
    - CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o horcrux_pi
    - CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -o horcrux_bsd
    - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o horcrux_osx
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o horcrux.exe
  artifacts:
    name: horcrux
    paths:
     - horcrux
     - horcrux_pi
     - horcrux_bsd
     - horcrux_osx
     - horcrux.exe
