version: 2

upx:
  - enabled: true
    compress: best
    goos: [linux]

archives:
- formats: [binary]

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
      - openbsd
      - plan9
      - linux
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
